---
- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes
  notify:
    - nginx systemd

- name: Install Nginx Web Server on Debian Family
  apt:
    name=nginx
    state=latest
  when:
    ansible_os_family == "Debian"
  notify:
    - nginx systemd

- name: Replace nginx.conf
  template:
    src=templates/nginx.conf
    dest=/etc/nginx/nginx.conf

- name: Create home directory for www
  file:
    path: /var/www/{{ virtual_domain }}
    state: directory

- name: Copy home directory for www
  template:
    src=templates/index.php
    dest=/var/www/html/index.php

- name: Add virtual domain in NGINX for Deb
  vars:
    fastcgi_pass_path: /run/php/php7.2-fpm.sock
  template:
    src=templates/nginx_vhosts.conf
    dest=/etc/nginx/sites-enabled/{{ virtual_domain }}.conf
  when:
    ansible_os_family == "Debian"
  notify:
    - nginx restart